/*
 * generated by Xtext 2.23.0
 */
package bimMixer.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBIMMixerAppScopeProvider extends DelegatingScopeProvider {
}
