/*
 * generated by Xtext 2.23.0
 */
package bimMixer.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BIMMixerAppUiModule extends AbstractBIMMixerAppUiModule {

	public BIMMixerAppUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
