/*
 * generated by Xtext 2.23.0
 */
package bimMixer.ide;

import bimMixer.BIMMixerAppRuntimeModule;
import bimMixer.BIMMixerAppStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BIMMixerAppIdeSetup extends BIMMixerAppStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BIMMixerAppRuntimeModule(), new BIMMixerAppIdeModule()));
	}
	
}
