<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BIMMixer" nsURI="bimmixer" nsPrefix="bimmixer">
  <eClassifiers xsi:type="ecore:EClass" name="BIMMixerApp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="certifications" upperBound="2"
        eType="#//BIMCertification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BIMCertification" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Categories" lowerBound="1"
        upperBound="-1" eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedCertification"
        eType="#//BIMCertification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BreeamCertification" eSuperTypes="#//BIMCertification"/>
  <eClassifiers xsi:type="ecore:EClass" name="LEEDCertification" eSuperTypes="#//BIMCertification"/>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCategories" lowerBound="1"
        upperBound="-1" eType="#//Subcategory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subcategory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="#//Subcategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obtainedPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
