/*
 * generated by Xtext 2.23.0
 */
package bimMixer.ui;

import bimMixerXtext.ui.internal.BimMixerXtextActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BIMMixerAppExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BimMixerXtextActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BimMixerXtextActivator activator = BimMixerXtextActivator.getInstance();
		return activator != null ? activator.getInjector(BimMixerXtextActivator.BIMMIXER_BIMMIXERAPP) : null;
	}

}
