/*
 * generated by Xtext 2.23.0
 */
package bimMixer.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class BIMMixerAppProposalProvider extends AbstractBIMMixerAppProposalProvider {
}
