//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace DemoNMF.FSM
{
    
    
    public class StateIncomingCollection : ObservableOppositeOrderedSet<IState, ITransition>
    {
        
        public StateIncomingCollection(IState parent) : 
                base(parent)
        {
        }
        
        private void OnItemDeleted(object sender, System.EventArgs e)
        {
            this.Remove(((ITransition)(sender)));
        }
        
        protected override void SetOpposite(ITransition item, IState parent)
        {
            if ((parent != null))
            {
                item.Deleted += this.OnItemDeleted;
                item.Target = parent;
            }
            else
            {
                item.Deleted -= this.OnItemDeleted;
                if ((item.Target == this.Parent))
                {
                    item.Target = parent;
                }
            }
        }
    }
}

