/*
 * generated by Xtext 2.23.0
 */
package bimMixer.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BIMMixerAppAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("bimMixer/parser/antlr/internal/InternalBIMMixerApp.tokens");
	}
}
