/*
 * generated by Xtext 2.23.0
 */
package bimMixer.parser.antlr;

import bimMixer.parser.antlr.internal.InternalBIMMixerAppParser;
import bimMixer.services.BIMMixerAppGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BIMMixerAppParser extends AbstractAntlrParser {

	@Inject
	private BIMMixerAppGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBIMMixerAppParser createParser(XtextTokenStream stream) {
		return new InternalBIMMixerAppParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BIMMixerApp";
	}

	public BIMMixerAppGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BIMMixerAppGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
