/*
 * generated by Xtext 2.23.0
 */
package bimMixer;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BIMMixerAppStandaloneSetup extends BIMMixerAppStandaloneSetupGenerated {

	public static void doSetup() {
		new BIMMixerAppStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
