//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace pruebasConsola.GameCreator
{
    
    
    /// <summary>
    /// The public interface for Game
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Game))]
    [XmlDefaultImplementationTypeAttribute(typeof(Game))]
    public interface IGame : IModelElement
    {
        
        /// <summary>
        /// The welcomeMsg property
        /// </summary>
        [DisplayNameAttribute("welcomeMsg")]
        [CategoryAttribute("Game")]
        [XmlElementNameAttribute("welcomeMsg")]
        [XmlAttributeAttribute(true)]
        string WelcomeMsg
        {
            get;
            set;
        }
        
        /// <summary>
        /// The locations property
        /// </summary>
        [LowerBoundAttribute(1)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("locations")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<ILocation> Locations
        {
            get;
        }
        
        /// <summary>
        /// The tests property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("tests")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<ITest> Tests
        {
            get;
        }
        
        /// <summary>
        /// The initialTest property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("initialTest")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        ITest InitialTest
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the WelcomeMsg property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WelcomeMsgChanging;
        
        /// <summary>
        /// Gets fired when the WelcomeMsg property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WelcomeMsgChanged;
        
        /// <summary>
        /// Gets fired before the InitialTest property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InitialTestChanging;
        
        /// <summary>
        /// Gets fired when the InitialTest property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InitialTestChanged;
    }
}

